# Series

In [1]:
# %pip install pandas
import pandas as pd
seriesa = pd.Series( [10, 20, 30] )
sorted(seriesa)

[10, 20, 30]

In [2]:
seriesa[0]

np.int64(10)

In [3]:
seriesa.loc(0)

In [4]:
seriesa + seriesa

0    20
1    40
2    60
dtype: int64

In [5]:
list(zip(seriesa))

[(10,), (20,), (30,)]

# Dataframe

In [6]:
data = pd.DataFrame({
    "Product": ["Pearls", "Cup", "Tea"],
    "Price": [100, 25, 300],
})

In [7]:
# Unsure of usage data.query("Product = Pearls")
data.shape

(3, 2)

In [8]:
data.columns

Index(['Product', 'Price'], dtype='str')

In [9]:
data.iloc[2:3]

  Product  Price
2     Tea    300

In [10]:
data = {
    "Serial No.": [1, 2, 3, 4, 5],
    "gre score": [337, 324, 316, 322, 314],
    "toefl score": [118, 107, 104, 110, 103],
}
df = pd.DataFrame(data).set_index("Serial No.")

In [11]:
df[(df['toefl score'] > 105) & (df['toefl score'] < 115)]

            gre score  toefl score
Serial No.
2                 324          107
4                 322          110

In [12]:
type(df)
df.shape

(5, 2)